server:
  port: 8080

spring:
  data:
    web:
      pageable:
        size-parameter: page-size
        one-indexed-parameters: 'true'
        page-parameter: page

    mongodb:
      uri: mongodb://admin:admin!@catalog_mongodb:27017/catalog

    redis:
      host: catalog_redis
      ssl: 'false'
      port: '6379'
      jedis:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
  cache:
    type: redis
    redis:
      time-to-live: '20000'

gateway:
  host: localhost
clock:
  timezone: UTC




