spring:
  profiles:
    active: @spring.profile@
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

server:
  max-http-header-size: 40KB
  servlet:
    context-path: /catalog-api

application-version: @project.version@





