#!/bin/bash

# Perform tests. On fail, this will print info about failed tests.

echo "Running all tests"
mvn clean test
if [ $? -ne 0 ]; then
    echo "Aborting push due to failed tests."
    exit 1
fi