version: '3'
services:

  catalog_mongodb:
    image: mongo:6.0
    container_name: catalog_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin!
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - ./mmongodb/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-compose-network

  catalog_mongo_express:
    image: mongo-express:1.0.0
    container_name: catalog_mongo_express
    ports:
      - 8086:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: catalog_mongodb
      ME_CONFIG_BASICAUTH_USERNAME: dev
      ME_CONFIG_BASICAUTH_PASSWORD: dev!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin!
    links:
      - catalog_mongodb
    networks:
      - mongo-compose-network

  catalog_redis:
    container_name: catalog_redis
    image: redis
    ports:
      - "6379:6379"

volumes:
  cache:
    driver: local
networks:
  mongo-compose-network:
    driver: bridge
